server:
  port: 8282
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:students_db
    username: sa
    password:
  h2:
    console:
      enabled: true